# Generated by Django 3.0.7 on 2020-07-05 17:44

from django.db import migrations

from openwisp_radius.migrations import popluate_uuids


class Migration(migrations.Migration):

    dependencies = [
        ('sample_radius', '0003_add_null_uuid_field'),
    ]

    operations = [migrations.RunPython(popluate_uuids)]
