# Generated by Django 3.0.7 on 2020-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_radius', '0003_default_groups_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationradiussettings',
            name='allowed_mobile_prefixes',
            field=models.TextField(
                blank=True,
                help_text=(
                    'Comma separated list of international mobile prefixes to '
                    'be restricted.'
                ),
                null=True,
            ),
        ),
    ]
