# Generated by Django 3.1.6 on 2021-02-10 13:16

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):
    dependencies = [
        ('sample_radius', '0020_added_optional_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationradiussettings',
            name='registration_enabled',
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text='Whether the registration API endpoint should be enabled or '
                'not',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='organizationradiussettings',
            name='saml_registration_enabled',
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text='Whether the registration using SAML should be enabled or not',
                null=True,
                verbose_name=_('SAML registration enabled'),
            ),
        ),
        migrations.AddField(
            model_name='organizationradiussettings',
            name='social_registration_enabled',
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text='Whether the registration using social applications should be enabled or not',
                null=True,
            ),
        ),
    ]
