# Generated by Django 3.1.7 on 2021-02-26 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sample_radius', '0021_organizationradiussettings_registration_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationradiussettings',
            name='needs_identity_verification',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='Whether identity verification is required at the time'
                ' of user registration',
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'identity_verification',
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, 'No Identity Verification'),
                            ('mobile', 'Mobile Phone'),
                        ],
                        default=None,
                        max_length=64,
                        null=True,
                    ),
                ),
                ('is_verified', models.BooleanField(default=False)),
                ('details', models.CharField(blank=True, max_length=64, null=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Identity Verification',
                'verbose_name_plural': 'Identity Verification',
                'abstract': False,
            },
        ),
    ]
