# Generated by Django 3.1.13 on 2021-12-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sample_radius', '0026_password_reset_url_org_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiuscheck',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='radiuscheck',
            name='valid_until',
        ),
        migrations.AlterField(
            model_name='radiuscheck',
            name='attribute',
            field=models.CharField(max_length=64, verbose_name='attribute'),
        ),
    ]
