# Generated by Django 4.2.17 on 2025-01-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sample_radius",
            "0029_alter_organizationradiussettings_allowed_mobile_prefixes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="radiusaccounting",
            name="called_station_id",
            field=models.CharField(
                blank=True,
                db_column="calledstationid",
                db_index=True,
                max_length=253,
                null=True,
                verbose_name="called station ID",
            ),
        ),
        migrations.AlterField(
            model_name="radiusaccounting",
            name="calling_station_id",
            field=models.CharField(
                blank=True,
                db_column="callingstationid",
                db_index=True,
                max_length=253,
                null=True,
                verbose_name="calling station ID",
            ),
        ),
        migrations.AlterField(
            model_name="radiuspostauth",
            name="called_station_id",
            field=models.CharField(
                blank=True,
                db_column="calledstationid",
                max_length=253,
                null=True,
                verbose_name="called station ID",
            ),
        ),
        migrations.AlterField(
            model_name="radiuspostauth",
            name="calling_station_id",
            field=models.CharField(
                blank=True,
                db_column="callingstationid",
                max_length=253,
                null=True,
                verbose_name="calling station ID",
            ),
        ),
    ]
