# Generated by Django 5.2.5 on 2025-09-02 07:05

import re

import django.core.validators
from django.db import migrations

import openwisp_utils.fields
import openwisp_utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ("sample_radius", "0030_alter_radiusaccounting_called_station_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationradiussettings",
            name="token",
            field=openwisp_utils.fields.KeyField(
                default=openwisp_utils.utils.get_random_key,
                help_text=None,
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(r"^[^\s/\.]+$"),
                        code="invalid",
                        message="This value must not contain spaces, dots or slashes.",
                    )
                ],
            ),
        ),
    ]
