# Generated by Django 5.2.5 on 2025-12-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample_radius", "0031_alter_organizationradiussettings_token"),
        ("sample_radius", "0031_radiusbatch_status"),
    ]

    operations = []
