# Generated by Django 5.2.9 on 2026-02-13 18:15

import django.core.serializers.json
from django.db import connection, migrations, models


def convert_text_to_jsonb_postgresql(apps, schema_editor):
    """
    Convert text columns to jsonb for PostgreSQL.
    This is necessary when migrating from jsonfield.fields.JSONField
    (which uses text) to Django's models.JSONField (which uses jsonb).
    """
    if connection.vendor != "postgresql":
        return

    with connection.cursor() as cursor:
        # Convert sms_meta_data column from text to jsonb
        cursor.execute("""
            ALTER TABLE sample_radius_organizationradiussettings
            ALTER COLUMN sms_meta_data TYPE jsonb USING sms_meta_data::jsonb
        """)
        # Convert user_credentials column from text to jsonb
        cursor.execute("""
            ALTER TABLE sample_radius_radiusbatch
            ALTER COLUMN user_credentials TYPE jsonb USING user_credentials::jsonb
        """)


def reverse_jsonb_to_text_postgresql(apps, schema_editor):
    """
    Reverse migration: convert jsonb columns back to text for PostgreSQL.
    """
    if connection.vendor != "postgresql":
        return

    with connection.cursor() as cursor:
        # Convert sms_meta_data column from jsonb to text
        cursor.execute("""
            ALTER TABLE sample_radius_organizationradiussettings
            ALTER COLUMN sms_meta_data TYPE text USING sms_meta_data::text
        """)
        # Convert user_credentials column from jsonb to text
        cursor.execute("""
            ALTER TABLE sample_radius_radiusbatch
            ALTER COLUMN user_credentials TYPE text USING user_credentials::text
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("sample_radius", "0031_radiusbatch_status"),
    ]

    operations = [
        # First, convert the PostgreSQL column types from text to jsonb
        migrations.RunPython(
            convert_text_to_jsonb_postgresql,
            reverse_code=reverse_jsonb_to_text_postgresql,
        ),
        # Then update the Django field definitions
        migrations.AlterField(
            model_name="organizationradiussettings",
            name="sms_meta_data",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text=(
                    "Additional configuration for SMS backend in JSON format "
                    "(optional, leave blank if unsure)"
                ),
                null=True,
                verbose_name="SMS meta data",
            ),
        ),
        migrations.AlterField(
            model_name="radiusbatch",
            name="user_credentials",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="PDF",
            ),
        ),
    ]
