x-timeseries:
  database: &timeseries_database ${TIMESERIES_DB:-openwisp2}
  username: &timeseries_username ${TIMESERIES_USER:-openwisp}
  password: &timeseries_password ${TIMESERIES_PASSWORD:-openwisp}
  org: &timeseries_org ${INFLUXDB2_ORG:-openwisp}
  token: &influxdb2_token ${INFLUXDB2_TOKEN:-openwisp-token}

services:
  influxdb:
    image: influxdb:1.8-alpine
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: *timeseries_database
      INFLUXDB_USER: *timeseries_username
      INFLUXDB_USER_PASSWORD: *timeseries_password

  influxdb2:
    image: influxdb:2.9.1-alpine
    volumes:
      - influxdb2-data:/var/lib/influxdb2
    ports:
      - "8087:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: *timeseries_username
      DOCKER_INFLUXDB_INIT_PASSWORD: *timeseries_password
      DOCKER_INFLUXDB_INIT_ORG: *timeseries_org
      DOCKER_INFLUXDB_INIT_BUCKET: *timeseries_database
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: *influxdb2_token

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-9.4.3}
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes

volumes:
  influxdb-data: {}
  influxdb2-data: {}
  elasticsearch-data: {}
