services:
  influxdb:
    image: influxdb:1.8-alpine
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: openwisp2
      INFLUXDB_USER: openwisp
      INFLUXDB_USER_PASSWORD: openwisp
    networks:
      - openwisp

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - openwisp

  radius:
    build:
      context: .
      dockerfile: Dockerfile
    image: openwisp-radius-dev
    working_dir: /opt/openwisp/tests
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/openwisp/
    depends_on:
      - redis
      - influxdb
    networks:
      - openwisp

volumes:
  influxdb-data:

networks:
  openwisp:
    driver: bridge
