#!/bin/bash
set -e

coverage run runtests.py --parallel > /dev/null 2>&1 || ./runtests.py
SAMPLE_APP=1 coverage run ./runtests.py --parallel > /dev/null 2>&1 || SAMPLE_APP=1 ./runtests.py
MONITORING_INTEGRATION=1 coverage run runtests.py
coverage combine
coverage xml
