# Generated by Django 5.2.13 on 2026-06-25 01:50

import swapper
from django.db import migrations


class Migration(migrations.Migration):
    org_model = swapper.get_model_name("openwisp_users", "organization")
    dependencies = [
        ("authtoken", "0004_alter_tokenproxy_options"),
        swapper.dependency(*swapper.split(org_model), version="0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[],
            options={
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("authtoken.token",),
        ),
    ]
