# Generated by Django 5.2.15 on 2026-07-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_users", "0004_default_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationuser",
            name="is_admin",
            field=models.BooleanField(
                default=False, verbose_name="Organization manager"
            ),
        ),
    ]
