# Generated by Django 4.2.3 on 2023-08-09 13:56

import swapper
from django.db import migrations

from . import create_general_metrics, delete_general_metrics


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        swapper.dependency('monitoring', 'Metric'),
        swapper.dependency('monitoring', 'Chart'),
    ]

    operations = [
        migrations.RunPython(
            create_general_metrics, reverse_code=delete_general_metrics
        )
    ]
