# Generated by Django 2.1.1 on 2018-09-18 17:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import openwisp_radius.models
import openwisp_users.mixins
import re
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_users', '0002_auto_20180508_2017'),
        ('openwisp_radius', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRadiusSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token', models.CharField(default=openwisp_radius.models.generate_token, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[^\\s/\\.]+$'), code='invalid', message='Key must not contain spaces, dots or slashes.')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openwisp_users.Organization', verbose_name='organization')),
            ],
            options={
                'abstract': False,
            },
            bases=(openwisp_users.mixins.ValidateOrgMixin, models.Model),
        ),
    ]
