# Generated by Django 3.0.7 on 2020-06-08 13:52

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_radius', '0008_sms_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiusbatch',
            name='pdf',
        ),
        migrations.AddField(
            model_name='radiusbatch',
            name='user_credentials',
            field=jsonfield.fields.JSONField(
                blank=True,
                null=True,
                verbose_name='PDF',
            ),
        ),
    ]
