# Generated by Django 3.0.7 on 2020-07-05 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_radius', '0009_radbatch_user_credentials_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='nas',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name='radiuscheck',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name='radiusgroupcheck',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name='radiusgroupreply',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name='radiuspostauth',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name='radiusreply',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name='radiususergroup',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, serialize=False
            ),
        ),
    ]
