# Generated by Django 3.0.7 on 2020-07-05 17:44

from django.db import migrations

from . import popluate_uuids


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_radius', '0011_add_null_uuid_field'),
    ]

    operations = [migrations.RunPython(popluate_uuids)]
