# Generated by Django 3.0.7 on 2020-07-05 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_radius', '0011_populate_uuid_field'),
    ]

    operations = [
        migrations.RemoveField(model_name='nas', name='id',),
        migrations.RemoveField(model_name='radiusaccounting', name='id',),
        migrations.RemoveField(model_name='radiuscheck', name='id',),
        migrations.RemoveField(model_name='radiusgroupcheck', name='id',),
        migrations.RemoveField(model_name='radiusgroupreply', name='id',),
        migrations.RemoveField(model_name='radiuspostauth', name='id',),
        migrations.RemoveField(model_name='radiusreply', name='id',),
        migrations.RemoveField(model_name='radiususergroup', name='id',),
        migrations.AlterField(
            model_name='nas',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='radiuscheck',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='radiusgroupcheck',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='radiusgroupreply',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='radiuspostauth',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='radiusreply',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='radiususergroup',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='unique_id',
            field=models.CharField(
                db_column='acctuniqueid',
                max_length=32,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name='accounting unique ID',
            ),
        ),
    ]
