# Generated by Django 5.2.13 on 2026-07-29 19:54
# flake8: noqa
# This is the second of two squash migrations. Migrations 0011-0013 stay
# separate because they safely update identifiers in existing FreeRADIUS tables.

import django
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models

import openwisp_radius.base.validators
import openwisp_radius.migrations
import openwisp_radius.registration
import openwisp_utils.fields
from openwisp_radius import settings as app_settings
from openwisp_utils.fields import FallbackMixin


def clean_fallback_fields(apps, schema_editor):
    OrganizationRadiusSettings = openwisp_radius.migrations.get_swapped_model(
        apps, "openwisp_radius", "OrganizationRadiusSettings"
    )
    fallback_fields = []
    for field in OrganizationRadiusSettings._meta.get_fields():
        if isinstance(field, FallbackMixin):
            fallback_fields.append(field)
    updated_settings = []
    for radius_settings in OrganizationRadiusSettings.objects.iterator():
        changed = False
        for field in fallback_fields:
            if getattr(radius_settings, field.name) == field.fallback:
                setattr(radius_settings, field.name, None)
                changed = True
        if changed:
            updated_settings.append(radius_settings)
        if len(updated_settings) > 100:
            OrganizationRadiusSettings.objects.bulk_update(
                updated_settings, fields=[field.name for field in fallback_fields]
            )
            updated_settings = []
    if updated_settings:
        OrganizationRadiusSettings.objects.bulk_update(
            updated_settings, fields=[field.name for field in fallback_fields]
        )


def set_existing_batches_completed(apps, schema_editor):
    RadiusBatch = openwisp_radius.migrations.get_swapped_model(
        apps, "openwisp_radius", "RadiusBatch"
    )
    RadiusBatch.objects.all().update(status="completed")


class Migration(migrations.Migration):

    replaces = [
        ("openwisp_radius", "0014_radiustoken_freeradius_auth"),
        ("openwisp_radius", "0015_freeradius_allowed_hosts"),
        ("openwisp_radius", "0016_allowed_mobile_prefixes"),
        ("openwisp_radius", "0017_phonetoken_phone_number"),
        ("openwisp_radius", "0018_populate_phonetoken_phone_number"),
        ("openwisp_radius", "0019_made_phonetoken_phone_number_required"),
        ("openwisp_radius", "0020_added_optional_registration_fields"),
        ("openwisp_radius", "0021_radius_user_group_unique_together"),
        ("openwisp_radius", "0022_organizationradiussettings_registration_enabled"),
        ("openwisp_radius", "0023_registered_user"),
        ("openwisp_radius", "0024_registereduser_modified"),
        ("openwisp_radius", "0025_sms_verification"),
        ("openwisp_radius", "0026_login_status_url_org_settings"),
        ("openwisp_radius", "0027_password_reset_url_org_settings"),
        (
            "openwisp_radius",
            "0028_organizationradiussettings_saml_social_registration_enabled",
        ),
        ("openwisp_radius", "0029_remove_check_customizations"),
        ("openwisp_radius", "0030_remove_radiuscheck_notes"),
        ("openwisp_radius", "0031_added_fallback_model_fields"),
        ("openwisp_radius", "0032_organizationradiussettings_sms_message"),
        ("openwisp_radius", "0033_alter_organizationradiussettings_password_reset_url"),
        ("openwisp_radius", "0034_organizationradiussettings_coa_enabled"),
        ("openwisp_radius", "0035_organizationradiussettings_sms_cooldown"),
        ("openwisp_radius", "0036_organizationradiussettings_mac_addr_roaming_enabled"),
        (
            "openwisp_radius",
            "0037_alter_organizationradiussettings_allowed_mobile_prefixes_and_more",
        ),
        ("openwisp_radius", "0038_clean_fallbackfields"),
        ("openwisp_radius", "0039_alter_radiusaccounting_called_station_id_and_more"),
        ("openwisp_radius", "0040_rename_phonetoken_index"),
        ("openwisp_radius", "0041_radiusbatch_status"),
        ("openwisp_radius", "0042_set_existing_batches_completed"),
    ]

    dependencies = [
        ("openwisp_radius", "0013_remove_null_uuid_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=openwisp_radius.migrations.delete_old_radius_token,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="radiustoken",
            name="can_auth",
            field=models.BooleanField(
                default=False,
                help_text="Enable the radius token to be used for freeradius authorization request",
            ),
        ),
        migrations.AddField(
            model_name="radiustoken",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="openwisp_users.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="freeradius_allowed_hosts",
            field=models.TextField(
                blank=True,
                help_text="Comma separated list of IP addresses allowed to access freeradius API",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="allowed_mobile_prefixes",
            field=models.TextField(
                blank=True,
                help_text="Comma separated list of international mobile prefixes allowed to register via the user registration API.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="phonetoken",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.RunPython(
            code=openwisp_radius.migrations.populate_phonetoken_phone_number,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="phonetoken",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
        migrations.AlterUniqueTogether(
            name="radiususergroup",
            unique_together={("user", "group")},
        ),
        migrations.CreateModel(
            name="RegisteredUser",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="registered_user",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=(
                            openwisp_radius.registration.REGISTRATION_METHOD_CHOICES
                            if django.VERSION < (5, 0)
                            else openwisp_radius.registration.get_registration_choices
                        ),
                        default="",
                        help_text="users can sign up in different ways, some methods are valid as indirect identity verification (eg: mobile phone SIM card in most countries)",
                        max_length=64,
                        verbose_name="registration method",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="whether the user has completed any identity verification process sucessfully",
                        verbose_name="verified",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Last verification change",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registration Information",
                "verbose_name_plural": "Registration Information",
                "abstract": False,
                "swappable": "OPENWISP_RADIUS_REGISTEREDUSER_MODEL",
            },
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="login_url",
            field=models.URLField(
                blank=True,
                help_text="Enter the URL where users can log in to the wifi service",
                null=True,
                verbose_name="Login URL",
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="status_url",
            field=models.URLField(
                blank=True,
                help_text="Enter the URL where users can log out from the wifi service",
                null=True,
                verbose_name="Status URL",
            ),
        ),
        migrations.RemoveField(
            model_name="radiuscheck",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="radiuscheck",
            name="valid_until",
        ),
        migrations.AlterField(
            model_name="radiuscheck",
            name="attribute",
            field=models.CharField(max_length=64, verbose_name="attribute"),
        ),
        migrations.RemoveField(
            model_name="radiuscheck",
            name="notes",
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="birth_date",
            field=openwisp_utils.fields.FallbackCharChoiceField(
                blank=True,
                choices=[
                    ("disabled", "Disabled"),
                    ("allowed", "Allowed"),
                    ("mandatory", "Mandatory"),
                ],
                default=None,
                fallback=app_settings.OPTIONAL_REGISTRATION_FIELDS.get("birth_date"),
                help_text="Whether this field should be disabled, allowed or mandatory in the user registration API.",
                max_length=12,
                null=True,
                verbose_name="birth date",
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="first_name",
            field=openwisp_utils.fields.FallbackCharChoiceField(
                blank=True,
                choices=[
                    ("disabled", "Disabled"),
                    ("allowed", "Allowed"),
                    ("mandatory", "Mandatory"),
                ],
                default=None,
                fallback=app_settings.OPTIONAL_REGISTRATION_FIELDS.get("first_name"),
                help_text="Whether this field should be disabled, allowed or mandatory in the user registration API.",
                max_length=12,
                null=True,
                verbose_name="first name",
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="last_name",
            field=openwisp_utils.fields.FallbackCharChoiceField(
                blank=True,
                choices=[
                    ("disabled", "Disabled"),
                    ("allowed", "Allowed"),
                    ("mandatory", "Mandatory"),
                ],
                default=None,
                fallback=app_settings.OPTIONAL_REGISTRATION_FIELDS.get("last_name"),
                help_text="Whether this field should be disabled, allowed or mandatory in the user registration API.",
                max_length=12,
                null=True,
                verbose_name="last name",
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="location",
            field=openwisp_utils.fields.FallbackCharChoiceField(
                blank=True,
                choices=[
                    ("disabled", "Disabled"),
                    ("allowed", "Allowed"),
                    ("mandatory", "Mandatory"),
                ],
                default=None,
                fallback=app_settings.OPTIONAL_REGISTRATION_FIELDS.get("location"),
                help_text="Whether this field should be disabled, allowed or mandatory in the user registration API.",
                max_length=12,
                null=True,
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="needs_identity_verification",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=app_settings.NEEDS_IDENTITY_VERIFICATION,
                help_text="Whether identity verification is required at the time of user registration",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="registration_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=app_settings.REGISTRATION_API_ENABLED,
                help_text="Whether the registration API endpoint should be enabled or not",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="saml_registration_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=app_settings.SAML_REGISTRATION_ENABLED,
                help_text="Whether the registration using SAML should be enabled or not",
                null=True,
                verbose_name="SAML registration enabled",
            ),
        ),
        migrations.AlterField(
            model_name="organizationradiussettings",
            name="sms_verification",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=app_settings.SMS_VERIFICATION_ENABLED,
                help_text="Whether users who sign up should be required to verify their mobile phone number via SMS",
                null=True,
                verbose_name="SMS verification",
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="social_registration_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=app_settings.SOCIAL_REGISTRATION_ENABLED,
                help_text="Whether the registration using social applications should be enabled or not",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="sms_message",
            field=openwisp_utils.fields.FallbackTextField(
                blank=True,
                default=None,
                fallback=app_settings.SMS_MESSAGE_TEMPLATE,
                help_text='SMS message template used for sending verification code. Must contain "{code}" placeholder for OTP value.',
                max_length=160,
                null=True,
                verbose_name="SMS Message",
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="coa_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=app_settings.COA_ENABLED,
                help_text="Whether RADIUS Change Of Authoization (CoA) is enabled",
                null=True,
                verbose_name="CoA Enabled",
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="sms_cooldown",
            field=openwisp_utils.fields.FallbackPositiveIntegerField(
                blank=True,
                default=None,
                fallback=app_settings.SMS_COOLDOWN,
                help_text="Time period a user will have to wait before requesting another SMS token (in seconds).",
                null=True,
                verbose_name="SMS Cooldown",
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="mac_addr_roaming_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=app_settings.MAC_ADDR_ROAMING_ENABLED,
                help_text="Whether the MAC address roaming should be enabled or not.",
                null=True,
                verbose_name="MAC address roaming enabled",
            ),
        ),
        migrations.AlterField(
            model_name="organizationradiussettings",
            name="allowed_mobile_prefixes",
            field=openwisp_utils.fields.FallbackTextField(
                blank=True,
                default=None,
                fallback=",".join(app_settings.ALLOWED_MOBILE_PREFIXES),
                help_text="Comma separated list of international mobile prefixes allowed to register via the user registration API.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organizationradiussettings",
            name="freeradius_allowed_hosts",
            field=openwisp_utils.fields.FallbackTextField(
                blank=True,
                default=None,
                fallback=",".join(app_settings.FREERADIUS_ALLOWED_HOSTS),
                help_text="Comma separated list of IP addresses allowed to access freeradius API",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationradiussettings",
            name="password_reset_url",
            field=openwisp_utils.fields.FallbackCharField(
                blank=True,
                default=None,
                fallback=app_settings.DEFAULT_PASSWORD_RESET_URL,
                help_text="Enter the URL where users can reset their password",
                max_length=200,
                null=True,
                validators=[
                    openwisp_radius.base.validators.password_reset_url_validator
                ],
                verbose_name="Password reset URL",
            ),
        ),
        migrations.RunPython(
            code=clean_fallback_fields,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="radiusaccounting",
            name="called_station_id",
            field=models.CharField(
                blank=True,
                db_column="calledstationid",
                db_index=True,
                max_length=253,
                null=True,
                verbose_name="called station ID",
            ),
        ),
        migrations.AlterField(
            model_name="radiusaccounting",
            name="calling_station_id",
            field=models.CharField(
                blank=True,
                db_column="callingstationid",
                db_index=True,
                max_length=253,
                null=True,
                verbose_name="calling station ID",
            ),
        ),
        migrations.AlterField(
            model_name="radiuspostauth",
            name="called_station_id",
            field=models.CharField(
                blank=True,
                db_column="calledstationid",
                max_length=253,
                null=True,
                verbose_name="called station ID",
            ),
        ),
        migrations.AlterField(
            model_name="radiuspostauth",
            name="calling_station_id",
            field=models.CharField(
                blank=True,
                db_column="callingstationid",
                max_length=253,
                null=True,
                verbose_name="calling station ID",
            ),
        ),
        migrations.RenameIndex(
            model_name="phonetoken",
            new_name="openwisp_ra_user_id_9fe207_idx",
            old_fields=("user", "created"),
        ),
        migrations.RenameIndex(
            model_name="phonetoken",
            new_name="openwisp_ra_user_id_d4dd52_idx",
            old_fields=("user", "created", "ip"),
        ),
        migrations.AddField(
            model_name="radiusbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.RunPython(
            code=set_existing_batches_completed,
        ),
    ]
