# Generated by Django 3.0.7 on 2020-10-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_radius', '0015_freeradius_allowed_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationradiussettings',
            name='allowed_mobile_prefixes',
            field=models.TextField(
                blank=True,
                help_text=(
                    'Comma separated list of international mobile prefixes to '
                    'be restricted.'
                ),
                null=True,
            ),
        ),
    ]
