# Generated by Django 3.1.2 on 2020-11-12 06:17

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_radius', '0018_populate_phonetoken_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
