# Generated by Django 3.1.5 on 2021-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_radius', '0019_made_phonetoken_phone_number_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationradiussettings',
            name='registration_api_enabled',
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text='Comma separated list of international mobile '
                'prefixes allowed to register via the user registration API.',
                null=True,
            ),
        ),
    ]
