# Generated by Django 3.1.13 on 2021-10-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_radius', '0023_registered_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='sms_verification',
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text=(
                    'whether users who sign up should be required to '
                    'verify their mobile phone number via SMS'
                ),
                null=True,
            ),
        ),
    ]
