# Generated by Django 3.1.10 on 2021-05-14 16:42

from django.db import migrations

import openwisp_radius.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_radius', '0022_organizationradiussettings_registration_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='allowed_mobile_prefixes',
            field=openwisp_radius.base.fields.FallbackTextField(
                blank=True,
                help_text='Comma separated list of international mobile prefixes allowed to register via the user registration API.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='birth_date',
            field=openwisp_radius.base.fields.FallbackChoiceField(
                blank=True,
                choices=[
                    ('disabled', 'Disabled'),
                    ('allowed', 'Allowed'),
                    ('mandatory', 'Mandatory'),
                ],
                help_text='Whether this field should be disabled, allowed or mandatory in the user registration API.',
                max_length=12,
                null=True,
                verbose_name='birth date',
            ),
        ),
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='first_name',
            field=openwisp_radius.base.fields.FallbackChoiceField(
                blank=True,
                choices=[
                    ('disabled', 'Disabled'),
                    ('allowed', 'Allowed'),
                    ('mandatory', 'Mandatory'),
                ],
                help_text='Whether this field should be disabled, allowed or mandatory in the user registration API.',
                max_length=12,
                null=True,
                verbose_name='first name',
            ),
        ),
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='freeradius_allowed_hosts',
            field=openwisp_radius.base.fields.FallbackTextField(
                blank=True,
                help_text='Comma separated list of IP addresses allowed to access freeradius API',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='last_name',
            field=openwisp_radius.base.fields.FallbackChoiceField(
                blank=True,
                choices=[
                    ('disabled', 'Disabled'),
                    ('allowed', 'Allowed'),
                    ('mandatory', 'Mandatory'),
                ],
                help_text='Whether this field should be disabled, allowed or mandatory in the user registration API.',
                max_length=12,
                null=True,
                verbose_name='last name',
            ),
        ),
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='location',
            field=openwisp_radius.base.fields.FallbackChoiceField(
                blank=True,
                choices=[
                    ('disabled', 'Disabled'),
                    ('allowed', 'Allowed'),
                    ('mandatory', 'Mandatory'),
                ],
                help_text='Whether this field should be disabled, allowed or mandatory in the user registration API.',
                max_length=12,
                null=True,
                verbose_name='location',
            ),
        ),
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='registration_enabled',
            field=openwisp_radius.base.fields.FallbackBooleanField(
                blank=True,
                choices=[
                    ('', 'Default (Enabled)'),
                    (True, 'Enabled'),
                    (False, 'Disabled'),
                ],
                help_text='Whether the registration API endpoint should be enabled or not',
                null=True,
            ),
        ),
    ]
