# Generated by Django 4.0.5 on 2022-11-04 14:53

from django.db import migrations

import openwisp_utils.fields
from openwisp_radius import settings as app_settings


class Migration(migrations.Migration):
    dependencies = [
        ('openwisp_radius', '0033_alter_organizationradiussettings_password_reset_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationradiussettings',
            name='coa_enabled',
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=app_settings.COA_ENABLED,
                help_text='Whether RADIUS Change Of Authoization (CoA) is enabled',
                null=True,
                verbose_name='CoA Enabled',
            ),
        ),
    ]
