# Generated by Django 3.2.21 on 2023-10-11 12:06

from django.db import migrations

import openwisp_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ('openwisp_radius', '0035_organizationradiussettings_sms_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationradiussettings',
            name='mac_addr_roaming_enabled',
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=False,
                help_text='Whether the MAC address roaming should be enabled or not.',
                null=True,
                verbose_name='MAC address roaming enabled',
            ),
        ),
    ]
