# Generated by Django 5.2 on 2025-04-09 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_radius", "0039_alter_radiusaccounting_called_station_id_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="phonetoken",
            new_name="openwisp_ra_user_id_9fe207_idx",
            old_fields=("user", "created"),
        ),
        migrations.RenameIndex(
            model_name="phonetoken",
            new_name="openwisp_ra_user_id_d4dd52_idx",
            old_fields=("user", "created", "ip"),
        ),
    ]
