# Generated by Django 5.2.5 on 2025-08-10 05:19

import json

from django.db import migrations, models


def convert_user_credentials_data(apps, schema_editor):
    RadiusBatch = apps.get_model("openwisp_radius", "RadiusBatch")
    for batch in RadiusBatch.objects.exclude(user_credentials__isnull=True):
        # Decode the double-encoded JSON
        try:
            decoded = json.loads(batch.user_credentials)
            batch.user_credentials = decoded
            batch.save(update_fields=["user_credentials"])
        except (json.JSONDecodeError, TypeError):
            # Skip if data is not valid JSON
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_radius", "0040_rename_phonetoken_index"),
    ]

    operations = [
        # Replace third-party JSONField with Django's built-in JSONField
        migrations.AlterField(
            model_name="radiusbatch",
            name="user_credentials",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="PDF",
            ),
        ),
        migrations.AlterField(
            model_name="organizationradiussettings",
            name="sms_meta_data",
            field=models.JSONField(
                blank=True,
                help_text="Additional configuration for SMS backend in JSON "
                "format (optional, leave blank if unsure)",
                null=True,
                verbose_name="SMS meta data",
            ),
        ),
        # Convert existing user_credentials data from double-encoded JSON
        migrations.RunPython(convert_user_credentials_data, migrations.RunPython.noop),
    ]
