# Generated by Django 5.2.5 on 2025-09-08 09:26

from django.db import migrations, models


def set_existing_batches_completed(apps, schema_editor):
    RadiusBatch = apps.get_model("openwisp_radius", "RadiusBatch")
    RadiusBatch.objects.all().update(status="completed")


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_radius", "0040_rename_phonetoken_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="radiusbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.RunPython(set_existing_batches_completed, migrations.RunPython.noop),
    ]
