# Generated by Django 5.2.5 on 2025-08-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_radius", "0040_rename_phonetoken_index"),
    ]

    operations = [
        # Replace third-party JSONField with Django's built-in JSONField
        migrations.AlterField(
            model_name='radiusbatch',
            name='user_credentials',
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name='PDF',
            ),
        ),
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='sms_meta_data',
            field=models.JSONField(
                blank=True,
                help_text='Additional configuration for SMS backend in JSON format (optional, leave blank if unsure)',
                null=True,
                verbose_name='SMS meta data',
            ),
        ),
    ]
