# Generated by Django 5.2.5 on 2025-09-29 13:48

from django.db import migrations


def set_existing_batches_completed(apps, schema_editor):
    RadiusBatch = apps.get_model("openwisp_radius", "RadiusBatch")
    RadiusBatch.objects.all().update(status="completed")


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_radius", "0041_radiusbatch_status"),
    ]

    operations = [
        migrations.RunPython(
            set_existing_batches_completed,
        ),
    ]
