# Generated by Django 5.2.5 on 2025-10-22 18:34

import json

from django.db import migrations, models


def convert_user_credentials_data(apps, schema_editor):
    """
    Convert existing double-encoded JSON strings in user_credentials field
    to proper JSON objects for Django's built-in JSONField.
    """
    RadiusBatch = apps.get_model("openwisp_radius", "RadiusBatch")
    for batch in RadiusBatch.objects.exclude(user_credentials__isnull=True):
        if isinstance(batch.user_credentials, str):
            try:
                batch.user_credentials = json.loads(batch.user_credentials)
                batch.save(update_fields=["user_credentials"])
            except (json.JSONDecodeError, TypeError):
                # If it's already decoded or invalid JSON, skip it
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_radius", "0042_set_existing_batches_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationradiussettings",
            name="sms_meta_data",
            field=models.JSONField(
                blank=True,
                help_text=(
                    "Additional configuration for SMS backend in JSON format "
                    "(optional, leave blank if unsure)"
                ),
                null=True,
                verbose_name="SMS meta data",
            ),
        ),
        migrations.AlterField(
            model_name="radiusbatch",
            name="user_credentials",
            field=models.JSONField(blank=True, null=True, verbose_name="PDF"),
        ),
        migrations.RunPython(
            convert_user_credentials_data, reverse_code=migrations.RunPython.noop
        ),
    ]
