# Generated by Django 5.2.11 on 2026-02-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_radius", "0042_set_existing_batches_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationradiussettings",
            name="sms_backend",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Optional dotted path to an SMS backend. "
                    "If empty, the global SMS_BACKEND setting is used."
                ),
                max_length=255,
            ),
        ),
    ]
