# Generated by Django 5.2.9 on 2026-02-03 08:05

from django.db import migrations

import openwisp_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_radius", "0042_set_existing_batches_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationradiussettings",
            name="cross_organization_login_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=True,
                help_text="Allow users already registered in another organization to log in without registering with this organization.",
                null=True,
                verbose_name="Cross-organization login enabled",
            ),
        ),
    ]
