# Generated by Django 5.2.5 on 2025-10-22 18:34

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_radius", "0042_set_existing_batches_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationradiussettings",
            name="sms_meta_data",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text=(
                    "Additional configuration for SMS backend in JSON format "
                    "(optional, leave blank if unsure)"
                ),
                null=True,
                verbose_name="SMS meta data",
            ),
        ),
        migrations.AlterField(
            model_name="radiusbatch",
            name="user_credentials",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="PDF",
            ),
        ),
    ]
