# Generated by Django 5.2.5 on 2025-12-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_radius", "0041_alter_organizationradiussettings_token"),
        ("openwisp_radius", "0042_set_existing_batches_completed"),
    ]

    operations = []
