# Generated by Django 5.2.5 on 2025-11-18 00:00

import json

from django.db import migrations


def convert_user_credentials_data(apps, schema_editor):
    """
    Convert existing double-encoded JSON strings in user_credentials field
    to proper JSON objects for Django's built-in JSONField.
    """
    RadiusBatch = apps.get_model("openwisp_radius", "RadiusBatch")
    for batch in RadiusBatch.objects.exclude(user_credentials__isnull=True).iterator():
        if isinstance(batch.user_credentials, str):
            batch.user_credentials = json.loads(batch.user_credentials)
            batch.save(update_fields=["user_credentials"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "openwisp_radius",
            "0043_alter_organizationradiussettings_sms_meta_data_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            convert_user_credentials_data, reverse_code=migrations.RunPython.noop
        ),
    ]
