# Generated by Django 5.2.9 on 2026-02-13 18:15

import json
import logging

import django.core.serializers.json
from django.db import migrations, models

logger = logging.getLogger(__name__)


def convert_user_credentials_data(apps, schema_editor):
    """
    Convert existing double-encoded JSON strings in user_credentials field
    to proper JSON objects for Django's built-in JSONField.
    """
    db_alias = schema_editor.connection.alias
    RadiusBatch = apps.get_model("openwisp_radius", "RadiusBatch")
    for batch in (
        RadiusBatch.objects.using(db_alias)
        .exclude(user_credentials__isnull=True)
        .iterator()
    ):
        if isinstance(batch.user_credentials, str):
            try:
                batch.user_credentials = json.loads(batch.user_credentials)
                batch.save(using=db_alias, update_fields=["user_credentials"])
            except Exception as e:
                logger.exception(f"Encountered error while processing {batch}: {e}")
                print(f"Encountered error while processing {batch}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        (
            "openwisp_radius",
            "0043_alter_organizationradiussettings_sms_meta_data_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationradiussettings",
            name="sms_meta_data",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text=(
                    "Additional configuration for SMS backend in JSON format "
                    "(optional, leave blank if unsure)"
                ),
                null=True,
                verbose_name="SMS meta data",
            ),
        ),
        migrations.AlterField(
            model_name="radiusbatch",
            name="user_credentials",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="PDF",
            ),
        ),
        migrations.RunPython(
            convert_user_credentials_data, reverse_code=migrations.RunPython.noop
        ),
    ]
