# Generated by Django 5.2.16 on 2026-08-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_radius", "0048_copy_batch_expiration_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="radiustoken",
            name="password_based",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text=(
                    "Indicates whether this radius token was issued after an"
                    " authentication which used the local password. When false, the"
                    " token was obtained through an external method (eg: SSO, SAML)"
                    " and the local password expiration policy does not apply to it."
                ),
                null=True,
            ),
        ),
    ]
