# Generated by Django 5.2.13 on 2026-08-18 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OPENWISP_RADIUS_RADIUSGROUP_MODEL),
        ("openwisp_radius", "0049_radiustoken_password_based"),
    ]

    operations = [
        migrations.AddField(
            model_name="radiusbatch",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.OPENWISP_RADIUS_RADIUSGROUP_MODEL,
                verbose_name="radius group",
            ),
        ),
        migrations.AddField(
            model_name="radiusbatch",
            name="notes",
            field=models.TextField(
                blank=True, help_text="internal notes", verbose_name="notes"
            ),
        ),
    ]
