---
name: OpenWISP RADIUS CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Python==${{ matrix.python-version }} | ${{ matrix.django-version }}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        django-version:
          - django~=3.2.0
          - django~=4.1.0
          - django~=4.2.0

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        id: deps
        run: |
          sudo apt update -qq
          sudo apt-get -qq -y install xmlsec1 gettext \
              sqlite3 \
              fping \
              gdal-bin \
              libproj-dev \
              libgeos-dev \
              libspatialite-dev \
              spatialite-bin \
              libsqlite3-mod-spatialite
          sudo npm install -g prettier
          pip install -U pip wheel setuptools
          pip install -U -r requirements-test.txt
          pip install -e .[saml,openvpn_status]
          pip install ${{ matrix.django-version }}

      - name: Start InfluxDB and Redis container
        run: docker compose up -d influxdb redis

      - name: QA checks
        run: |
          ./run-qa-checks

      - name: Tests
        if: ${{ !cancelled() && steps.deps.conclusion == 'success' }}
        run: |
          coverage run runtests.py --parallel > /dev/null 2>&1 || ./runtests.py
          SAMPLE_APP=1 coverage run ./runtests.py --parallel > /dev/null 2>&1 || SAMPLE_APP=1 ./runtests.py
          MONITORING_INTEGRATION=1 coverage run runtests.py
          coverage combine
          coverage xml
        env:
          SELENIUM_HEADLESS: 1
          GECKO_LOG: 1

      - name: Show gecko web driver log on failures
        if: ${{ failure() }}
        run: cat geckodriver.log

      - name: Upload Coverage
        if: ${{ !cancelled() && steps.deps.conclusion == 'success' }}
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          format: cobertura
          flag-name: python-${{ matrix.env.env }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  coveralls:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
