---
name: OpenWISP RADIUS CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Python==${{ matrix.python-version }} | ${{ matrix.django-version }}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        django-version:
          - django~=3.2.0
          - django~=4.1.0
          - django~=4.2.0

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install system libraries
        run: |
          sudo apt update
          sudo apt-get -qq -y install xmlsec1 gettext

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        id: deps
        run: |
          pip install -U pip wheel setuptools
          pip install -U -r requirements-test.txt
          pip install -e .[saml,openvpn_status]
          pip install ${{ matrix.django-version }}
          sudo npm install -g jslint

      - name: QA checks
        run: |
          ./run-qa-checks

      - name: Tests
        if: ${{ !cancelled() && steps.deps.conclusion == 'success' }}
        run: |
          coverage run --source=openwisp_radius runtests.py
          # SAMPLE tests do not influence coverage, so we can speed up tests with --parallel
          SAMPLE_APP=1 ./runtests.py --parallel --keepdb > /dev/null 2>&1 || SAMPLE_APP=1 ./runtests.py --keepdb
          coverage xml

      - name: Upload Coverage
        if: ${{ !cancelled() && steps.deps.conclusion == 'success' }}
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          format: cobertura
          flag-name: python-${{ matrix.env.env }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  coveralls:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
